### ISSUE TITLE
Not recognising database

### ISSUE THREAD

**Issue by Thewisem** [Divested-Mobile/hypatia#10]
It wouldn't scan my device because it doesn't recognise my database? I updated the database recently and its confusing why it still wouldn't see any databases
Device: Samsung Galaxy Tab A SM P555
OS: Android 7.1.1 Nougat

**Comment by SkewedZeppelin** [comment]
Can you clear app data, update database and attempt scan again?

If it fails can you post a screenshot?

**Comment by Thewisem** [comment]
I did clear app data, downloaded again and tried again

**Comment by Thewisem** [comment]
![Screenshot_20210610-221450](https://user-images.githubusercontent.com/74511929/121584637-5b15c780-ca3a-11eb-831a-7c396950b615.jpg)
Here

**Comment by SkewedZeppelin** [comment]
You cannot have daily enabled. Your device does not have enough RAM.
It truly as its description implies, is *very* large.

The default enabled databases are optimized for detection/performance. If you want some more detection of non-Android malware, you can enable main. But I strongly advise against enabling daily, unless your device has at least 6GB of RAM.

Daily, by the way gets updated no more frequently then the other databases, it is just a naming convention from ClamAV.

**Comment by Thewisem** [comment]
Oh ok

**Comment by Thewisem** [comment]
Yeah its fixed

**Comment by Thewisem** [comment]
Just one question. Hoe much would you say is the detection rate. Is it virustotal level or default android virus defender level?

**Comment by SkewedZeppelin** [comment]
Hypatia only operates on basic checksum databases.
Hard to say, honestly likely quite low.
Will not detect anything targeted.
Will only likely detect old and known/researched malware.

**Comment by ippocratis** [comment]
> Hypatia only operates on basic checksum databases.
> Hard to say, honestly likely quite low.
> Will not detect anything targeted.
> Will only likely detect old and known/researched malware.

This is probably also answers https://github.com/Divested-Mobile/Hypatia/issues/19
