### ISSUE TITLE
Extra signature databases

### ISSUE THREAD

**Issue by user8446** [Divested-Mobile/hypatia#12]
Hello,

After [reading this](https://stackoverflow.com/questions/54533862/clamav-singnature-list-for-android-apk) there is a comodo signature database that works w/ ClamAV which is [here](https://www.comodo.com/home/internet-security/updates/vdp/database.php). 
Is this a signature database that should be added to Hypatia?

**Comment by SkewedZeppelin** [comment]
I do not believe I can include that list, due to its license. And I do not see an easy way to extract it either.

However I do maintain a list of potentials:
https://github.com/Neo23x0/signature-base - CC BY-NC 4.0, with a GPL repo at an [older commit](https://github.com/Neo23x0/signature-base/tree/40b8f44c51bebb70c07b5f3fdf4d3f41e08cd9de~1)
https://github.com/amnestytech/investigations - Unknown - https://github.com/AmnestyTech/investigations/issues/11
https://github.com/avast/covid-19-ioc - Unknown - https://github.com/avast/covid-19-ioc/issues/1
https://github.com/citizenlab/malware-indicators - CC BY-NC 4.0
https://github.com/fireeye/iocs - Apache-2.0 - is very old
https://github.com/pan-unit42/iocs - MIT - is not very well structured
https://github.com/mbkore/lockup/blob/main/app/src/main/java/com/lockup/LockUpService.java#L54 - CC0?

I believe I can add CC BY-NC 4.0 databases, but they would likely have to be disabled by default, but I am not a lawyer.

Databases do not need to be in ClamAV format, I maintain conversion scripts as necessary here:
https://github.com/Divested-Mobile/Hypatia/tree/stable/scripts

**Comment by user8446** [comment]
I couldn't find license info either. The only thing I found was you can't use 3rd party signatures in their AV product: https://www.comodo.com/repository/docs/antivirus_eula.php but nothing on using their signatures in a 3rd party app.

That's a good list of potentials especially with the NSO Pegasus news going around.

**Comment by SkewedZeppelin** [comment]
Typically if something doesn't state a license it is ALL RIGHTS
RESERVED and cannot be used.

I will only add databases to this that are explicitely permissively
licensed.

Maybe in the future there will be support for custom user databases.

The 2nd link in that list has the known Pegasus hashes and the last one
has Cellebrite hashes, but with no defined or questionable license
cannot be added.

:(

**Comment by Obazzi** [comment]
@SkewedZeppelin 
> https://github.com/amnestytech/investigations - Unknown - [AmnestyTech/investigations#11](https://github.com/AmnestyTech/investigations/issues/11)

They do not recommend using this as a block list. See the following for reasoning: https://github.com/AmnestyTech/investigations/issues/4#issuecomment-888181343

**Comment by SkewedZeppelin** [comment]
@Obazzi Hypatia doesn't have anything to do with or block domains.

**Comment by Releece** [comment]
@SkewedZeppelin 
> Typically if something doesn't state a license it is ALL RIGHTS RESERVED and cannot be used. I will only add databases to this that are explicitely permissively licensed. Maybe in the future there will be support for custom user databases. The 2nd link in that list has the known Pegasus hashes and the last one has Cellebrite hashes, but with no defined or questionable license cannot be added. :(

Hi Tad, do I understand it correctly that it is not possible for a user to add either a custom database file *.cav or a link to such a database? I understand the license problem, you can't put those databases on the public server, but wouldn't that be a very good reason for letting users add custom databases by just specifying the link?

Then we would be able to make use of vastly more malware definitions :D

PS: I see the database server override option, but this seems like it only lets you point to a single link, so I would then lose all the databases that are included with Hypatia in favor of the ones found at the newly specified link?
What does Hypatia expect to find at the specified link? A folder with database files? Or a HTML page with links to databases separated by line or sth?

**Comment by Releece** [comment]
@SkewedZeppelin 
> Typically if something doesn't state a license it is ALL RIGHTS RESERVED and cannot be used. I will only add databases to this that are explicitely permissively licensed. Maybe in the future there will be support for custom user databases. The 2nd link in that list has the known Pegasus hashes and the last one has Cellebrite hashes, but with no defined or questionable license cannot be added. :(

Hi Tad, do I understand it correctly that it is not possible for a user to add either a custom database file or a link to such a database? I understand the license problem, you can't put those databases on the public server / GitHub, but wouldn't that be a very good reason for letting users add custom databases by just specifying the link?

Then users would be able to make use of all public license- / rights-restricted malware definitions :D

PS: I see the database server override option, but this seems like it only lets you point to a single link, so I would then lose all the databases that are included with Hypatia in favor of the ones found at the newly specified link?
What does Hypatia expect to find at the specified link? A folder with database files? Or a HTML page with links to databases separated by line or sth?

**Comment by SkewedZeppelin** [comment]
@Releece 
there is currently no support for custom databases, but is something that ought to be added

the server override option also doesn't support custom databases, it expects it to have the same files generated from the scripts

**Comment by SkewedZeppelin** [comment]
Latest update includes numerous added databases: https://divested.dev/MalwareScannerSignatures/
