### ISSUE TITLE
App becoming unresponsive after clicking the scan button

### ISSUE THREAD

**Issue by erenmenges** [Divested-Mobile/hypatia#13]
Device: Samsung Galaxy S10
Version: Android 11

After updating databases and clicking the bottom right scan button, the app becomes unresponsive and does nothing. The upper right menu becomes unclickable. Using app version 2.21

**Comment by SkewedZeppelin** [comment]
If you enable too many databases (from the defaults) it can cause the
scan to not start. There will be a repeated "loading database" message.

If you have a lot of files, it can take a long while to start. In this
case there is currently no indication.
