### ISSUE TITLE
5 selectable databases != 10 databases to update

### ISSUE THREAD

**Issue by tr1v1n1ty** [Divested-Mobile/hypatia#15]
When I tap on "Select databases" in the top right options menu after loading the app, I am presented with five databases, each with a check box to toggle it on or off. _(fig.1)_

Then, after tapping on "Update databases," the log on the homepage outputs, "Updating 10 databases....." _(fig. 2)_

Seems pretty benign as it's just doing each twice, but I am curious what is causing it and if there are any material difference between the two.

Thanks for your hard work, I appreciate having something dependable that I know is always working in the background. Just a speck on my battery usage, too! 

![Screenshot_20220314-193510_Hypatia](https://user-images.githubusercontent.com/97569736/158283644-6026cff5-e477-4fe8-9963-d7c8c0ec7837.jpg)
fig.1

![Screenshot_20220314-193526_Hypatia](https://user-images.githubusercontent.com/97569736/158283672-c0372764-6f7c-47a6-b0dd-22b294ea5f43.jpg)
fig.2

**Comment by SkewedZeppelin** [comment]
It is correct.
Each database/source is split into two files: the hsb (sha1/256) and the hdb
(md5) hashes.

**Comment by tr1v1n1ty** [comment]
@SkewedZeppelin thank you, glad to learn that

**Comment by SkewedZeppelin** [comment]
It is correct.
Each database/source is split into two files: the hsb (sha1/256) and the hdb
(md5) hashes.
