### ISSUE TITLE
Why not available in Play Store?

### ISSUE THREAD

**Issue by dnet890** [Divested-Mobile/hypatia#20]
Hi
to increase the popularity of this app. I am just wondering: Why this app not in Play store?

**Comment by SkewedZeppelin** [comment]
Because people should be encouraged to not suffocate in walled gardens

**Comment by dnet890** [comment]
well, normal users or even someone who are not really tech-savvy in Android looking for app. Play Store is the number one place to look the app and no one really bother to install F-Droid as a workaround.

**Comment by leestarb** [comment]
Play store is not free
