### ISSUE TITLE
Start scan

### ISSUE THREAD

**Issue by octavo** [Divested-Mobile/hypatia#22]
If the user switches to another app during the scan, the scan results/screen/progress disappear(s).

to reproduce:
1. start scan
![img_1.png](https://user-images.githubusercontent.com/1730033/197175083-87df6835-cf51-45d5-8a58-813cc9893c1a.png)
2. switch to any other app
3. switch back to hypatia
4. scan gone 
![img_0.png](https://user-images.githubusercontent.com/1730033/197175030-2bb92b7d-5dd3-4385-bc98-ca097823c6fe.png)
5. ???

**Comment by SkewedZeppelin** [comment]
yes, this likely happens if the device has not enough ram to keep the scan running at the same time.

or if the vendor altered system aggressively reaps background apps.

**Comment by SkewedZeppelin** [comment]
this is less likely to happen on the latest versions due to the increased memory efficiency
