### ISSUE TITLE
Fails to detect test file

### ISSUE THREAD

**Issue by fohfuu** [Divested-Mobile/hypatia#27]
TA-1012 (Nokia 8); Android 9; PPR1.18.0610.011

Ver 2.29 (95) (via F-Droid)

### Expected Behaviour

The file /graphics/hypatia-test-file.xcf should trigger some sort of warning from Hypatia during Realtime Scan or a manual scan.
As it's a test file from 2021, it shouldn't be so new or obfuscated to go undetected.

### Unexpected Behaviour

The file /graphics/hypatia-test-file.xcf doesn't have any effect on Hypatia's Realtime Scan or on a manual scan.

<details>
<summary>Output example (after downloading databases on 16 Feb 2023)</summary>
<br>

```
Copyright 2017-2023 Divested Computing Group
License: GPL-3.0
Version: 2.29
Powered by ClamAV style signatures

Updating 7 databases...
amnesty.hsb.gz
	File not changed since 16 Feb 2023

targetedthreats.hsb.gz
	File not changed since 16 Feb 2023

targetedthreats.hdb.gz
	File not changed since 16 Feb 2023

eset.hdb.gz
	File not changed since 16 Feb 2023

eset.hsb.gz
	File not changed since 16 Feb 2023

Android.hsb.gz
	File not changed since 16 Feb 2023

Android.hdb.gz
	File not changed since 16 Feb 2023

Starting scan...
	41,239 files pending scan

	Loaded database with 453,908 signatures

	Hashing files...
	 ~  =  ~  =  ~  =  ~  =  ~  =  ~  =  ~  =  ~  =  ~  =  ~  =  !
	Calculated hashes for all files

	Checked all MD5 hashes against signature databases

	Checked all SHA-1 hashes against signature databases

	Checked all SHA-256 hashes against signature databases

Scan completed in 242 seconds @ 92MB/s!
```

</details>

### Other Information

• Storage permission is given.

• Clearing storage/cache does not solve this bug.

• Database selection left as default.

• Database server left as default.

• Download over Tor is unticked.

• Data usage for Hypatia shows that after updating the databases once, 430 kB data was transmitted and 19.02 MB received.

### Notes

• Possibly related? When closing/re-opening the app, Scan /system and Scan External Storage untick themselves. Changing apps while the app is open does not trigger this change. This happens after the app is closed or dropped, including when Realtime Scan is ticked and the notification visible.

• My gut reaction is that this Android 9 is incompatible with newer releases, but I haven't seen this mentioned anywhere and haven't tried earlier versions of Hypatia.

**Comment by SkewedZeppelin** [comment]
No, that file wouldn't be detected as it isn't the test file, this is: https://divestos.org/images/hypatia-test-file.png

>  including when Realtime Scan is ticked and the notification visible.

Realtime scanner only scans internal storage.

> Scan /system and Scan External Storage untick themselves. 

These are per scan options for the manual scan.

> Android 9 is incompatible with newer releases

I test all on Android 7.1.2 before release.

**Comment by fohfuu** [comment]
Ah - the PNG is indeed flagged `Hypatia-Test-Signature in ~/Download/hypatia-test-file.png`!

The other information was just to be thorough.

Thank you for your help!
