### ISSUE TITLE
Adding an Italian README.md & first drafts of a future Spanish translation

### ISSUE THREAD

**Issue by iNtEgraIR2021** [Divested-Mobile/hypatia#3]
Hi everyone,

looking at the recent translation of Hypatia into [Italian](https://github.com/Divested-Mobile/Hypatia/pull/2#issue-588598893) by @dantecpu , I thought that it might be helpful to translate the [README.md](https://github.com/Divested-Mobile/Hypatia/blob/stable/README.md) as well.

Same happened before with the German and French Translations.
Please see the attached first draft. As I unfortunately hardly speak Italian myself a review by @dantecpu and/or other participants is definitely needed for a later publication.

For some reason GitHub apparently blocks the upload of Markdown files as attachments 🤔 so I had to "convert" 😆 it to a TXT file. Same with the strings.xml file below. 😆 
![image](https://user-images.githubusercontent.com/80395360/111882998-f0b03680-89b8-11eb-8789-3ff4233260df.png)

[README.it.md](https://github.com/Divested-Mobile/Hypatia/files/6176250/README.it.md.txt)

I'll also reference this issue on the [GitLab repo](https://gitlab.com/divested-mobile/hypatia) to include everyone interested.

Btw as mentioned in the title I'm also thinking about adding a Spanish translation. I'll attach first drafts for the README.md and the strings.xml.

[strings.es.xml](https://github.com/Divested-Mobile/Hypatia/files/6176256/strings.es.xml.txt)

My knowledge of Spanish is unfortunately comparatively low like that of Italian. So if you are reading this and are a native speaker yourself: Please feel free to proofread the drafts and/or add your own suggestions. I'll be grateful for any support.

Regards, 👋🏼 
Petra

**Comment by iNtEgraIR2021** [comment]
Btw if anyone at GitHub reads this ... please consider adjusting the file upload policy/ies and/or the given hints.
I'm not a CyberSec professional nor a Dev myself but ... it's rather hard to believe that the potential damage caused by 
Markdown files  is higher than that caused by Text (txt) files. These are both static file types so I don't expect the'll contain any executable code. (For comparison GitLab accepts both)

I'd like to highlight that this my personal point-of-view and not be meant to be any offense to anyone in any way.
As I'm not affiliated with GitHub's internals in anyway I don't know about the technical or organisational background of this decision nor it's possible timeline or recent development. I'm rather knew to GitHub as a user so I might have missed anything obvious here.

I you do know about the background of this please feel free to reach out to me with further details.

Regards, Petra

**Comment by SkewedZeppelin** [comment]
Thank you for this!

I will wait a little for others to review it.
If not soon, there is no harm in merging.

**Comment by chaoscalm** [comment]
Merge good, add credits to @iNtEgraIR2021 for localizing it too

**Comment by SkewedZeppelin** [comment]
Thank you @dantecpu for reviewing.

I have pulled both in. They can always be revised later.

Thank you @iNtEgraIR2021 for your works!

**Comment by iNtEgraIR2021** [comment]
Thank you @dantecpu  for reviewing. 👍🏼 

Thank you @SkewedZeppelin for merging! 👍🏼 

Being translated to English. German, French, Italian and Spanish Hypatia should theorethicaly be usable by about a third of the world's population in their first-language according to this (rather dated) [Wikipedia](https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers) page. 🥳 

So big thanks to all.  👍🏼 

I'll close this issue now.
