### ISSUE TITLE
Did an exception occur during scanning? 

### ISSUE THREAD

**Issue by ConTexTINAI** [Divested-Mobile/hypatia#30]
Thank you very much for what you have done with Hypatia.

I have extremely limited knowledge with this kind of thing but I have been showing scans that end with an "!" after approximately 75% of the lateral movement of the scan progress indicator bar "~=" and I was wondering if this was perhaps due to a malicious feature of possible malware (broadly defined) stopping  the scan upon a triggering event by manipulating it to abort the scan, which causes the "!" (exception fault) with no further context or explanation? I have had Hypatia on my device for a while and several updates and I just seem to remember the "~=" progress bar characters always spanning the entire lateral width of my screen, which to me always felt like a good indication that the scan had compared hashes of 100% of my files.

Long time fan of Hypatia and GitHub and I am really sorry if I am asking a stupid question or it does not make sense. This is literally the first time I have ever created an issue 🤷🏼‍♂️

Thank you for your efforts towards trying to keep our devices more secure.

GitHub is not allowing me to attach my screenshot. Possible file size restrictions?

**Comment by SkewedZeppelin** [comment]
! denotes the end of the progress bar.
A scan should say "Scan completed" at the end.

If a match is found it will be printed after the progress bar and before the "Scan complete" message.

**Comment by ConTexTINAI** [comment]
Thank you for your prompt response! 

That is good to know. Fortunately, I do get all the output at the EOS indicating that the scan was completed - MD5 \ SHA-1 \ SHA-256 hashes all checked and the speed. Nothing flagged or anomalous output. 

Thanks again for clearing up my non-issue 🤦🏼‍♂️😅

**Comment by rmeissn** [comment]
It would be preferable to clearly label the test outcome. 
After installing the application today, I conducted a scan. Uncertain about the results, I sought to identify and clarify any potential issues. Having a printout that states either "Scan completed, no malware found" or "Scan completed, the following files are infected:" would be greatly appreciated!
