### ISSUE TITLE
Reboot system Problem 

### ISSUE THREAD

**Issue by joe2047** [Divested-Mobile/hypatia#32]
When i reboot android the Hypatia not automatic running.

Can fix it? 

I love this software
Thanks you

**Comment by SkewedZeppelin** [comment]
The realtime scanner option is enabled but it doesn't restart on boot?

Maybe try the steps here? https://dontkillmyapp.com/

**Comment by joe2047** [comment]
Ok , thanks

I think is android need sometimes to running application with this problem.

Than i want to know what's mean is it ( Against)?

When scanned

Checked all MD5 hashes against signature databases

	Checked all SHA-1 hashes against signature databases

	Checked all SHA-256 hashes against signature databases

Thanks

**Comment by SkewedZeppelin** [comment]
> Than i want to know what's mean is it ( Against)?

It means the files were checked against the database and no matches were found.
