### ISSUE TITLE
db downloaded twice v.2.31

### ISSUE THREAD

**Issue by islam2hamy** [Divested-Mobile/hypatia#33]
open the app
click update databases

**Comment by SkewedZeppelin** [comment]
It doesn't download twice, it downloads the database and a GPG signature of the database.
This is to ensure it wasn't tampered with.

**Comment by islam2hamy** [comment]
![IMG_٢٠٢٣٠٤٢٦_٠٣٣١٥٣](https://user-images.githubusercontent.com/7989030/234443217-e1e093f2-6525-42cd-806f-91fe45689a10.jpg)

?

**Comment by SkewedZeppelin** [comment]
There is nothing wrong there.

.hdb contains MD5 hashes, .hsb contains SHA hashes, each one also has a .sig file to ensure the hashes are correct and not modified/tampered in transit.

**Comment by islam2hamy** [comment]
Oh , sorry for that
i didn't see that it is .hdb and .hsb
