### ISSUE TITLE
Database update issue

### ISSUE THREAD

**Issue by E0697** [Divested-Mobile/hypatia#34]
Since v2.31 came out, the Android databases always fail to download:

Android.hdb.gz
Failed to download, check logcat

Android.hdb.gz.sig
Failed to download, check logcat

Android.hsb.gz
Failed to download, check logcat

Android.hsb.gz.sig
Failed to download, check logcat

In addition to those, a fifth file usually fails to download, sometimes a database, sometimes a signature. It's not constant.

[Logcat](https://nopaste.ml/#XQAAAQBIDAAAAAAAAAAYDUHcdGj+CSakbRcnD4mw8DJ79OTSWcXxtAFoNIMevHKfvnDCcmOJPD7h6Io8E0kClXPgHX9tsR5Vg1YpHvdJDVheo7sr+bGOhvLdf8zaOInb0RduIH9AZaGzyKJzHgvmAD817s4v+y3w4UtebsiDey1WgLSGcxB5yFJnUaI+y2j+j0aoTKlt7HLuEnHpFrjKVpQovVVKk8KzhrpE/emKGuSm5xSn0ZW3m5qrQKnZCw9lRhnyd41gywatFtSVXFOmIUEImgFFGjiK/5url5WMBQNis/TB9SuXiF+F5F9ZnOjl6Am7XuzwI/t9Rs7bMym5L4wrSLIIqMXg3wstPuyQvKP/9ObvQA==)

**Comment by SkewedZeppelin** [comment]
Are you able to access the divested.dev website in a browser when you get that error?

**Comment by E0697** [comment]
Yes, it loads normally.

**Comment by E0697** [comment]
This has been consistently the fifth file failing to download: daily.hsb.gz.sig

**Comment by Moonstone3010** [comment]
I have the same problem with version 2.32.  The first five files cannot be downloaded.

**Comment by SkewedZeppelin** [comment]
How old is your device? Is it pre Android 7.1.2?

I strongly suspect this isn't an app issue, but a server issue. I recently switched to ecdsa keys to reduce server load and perhaps older versions can't handle that.

**Comment by E0697** [comment]
Mine is Android 12.

**Comment by Moonstone3010** [comment]
> Mine is Android 12.

Same here.

**Comment by SkewedZeppelin** [comment]
I see no errors on the server end.

If you can download some databases but not others that rules out the certificate change.

The download handling code also hasn't changed in a long while.

I've slightly increased the rate limits on the server, please let me know if it still happens.
If it does try to open the divested.dev website in a browser within a 30 second window of the error and see if it loads or not.

**Comment by E0697** [comment]
Same thing. The website loads normally.

I just tried disabling the Daily and Main databases and it actually worked without any issues.
If I enable them back (either one or both) it fails again.

**Comment by E0697** [comment]
If I check the Download over Tor option, the app hangs app for a while. The system says it's not responding.
If I wait however, it eventually responds.

This decreases the number of failed downloads to one, mostly.

**Comment by SkewedZeppelin** [comment]
Oh interesting, with the defaults I can't reproduce. But with an extra database like main or daily I see the error.
Will try and fix.

edit: I see the issue, will fix.

**Comment by SkewedZeppelin** [comment]
A new build is up on my repo with this issue fixed.
It should land on official F-Droid repo in a few days.

Thanks for the reports!

**Comment by E0697** [comment]
Thank you too!
