### ISSUE TITLE
Add date of databases in the homescreen

### ISSUE THREAD

**Issue by racuna** [Divested-Mobile/hypatia#36]
In the homescreen there is a lot of black space (dark mode at least) that can be filled with some userful info, like when was the latest date of update by database: Clamav, Eset, etc.

In other topic, I will like to read a changelog in F-Droid, but it is not even an issue, just for curiosity.

Thanks for this app. :)

**Comment by SkewedZeppelin** [comment]
database date is already shown when updating databases.
current mechanism doesn't allow seeing original file date once already downloaded.
