### ISSUE TITLE
why hypatia stop a few times daily

### ISSUE THREAD

**Issue by 1alexman1** [Divested-Mobile/hypatia#40]
Hello to all,
I have a samsung A10 and I don't understand why hypatia stop so many times a day. 
I have to monitor and start it again, and this is not so good. The software is amazing and I wish to use it further.Thx

**Comment by SkewedZeppelin** [comment]
Do you have the main and daily databases enabled? They are *not* recommended and may result in the system killing the app.

**Comment by 1alexman1** [comment]
Yes I do. I've disabled now. I hope it won't stop again. I will monitor today and tommorow I will close the issue.
Thank you very much

**Comment by 1alexman1** [comment]
It works continuously.Thank you very much
