### ISSUE TITLE
Signatures to detect PEGASUS spyware

### ISSUE THREAD

**Issue by shivagnihotri** [Divested-Mobile/hypatia#41]
Thank you from Germany to all developers improving this wonderful tool! 🤗

Would you please add a signature database to Hypatia to ensure a deep scan for the PEGASUS spyware? You can grab the indicators from the [mvp project repository](https://github.com/mvt-project/mvt). ✅

The [Mobile Verification Toolkit](https://docs.mvt.re/en/latest/) has not yet released a working Android app to detect it.

Again: Thank you for all your awesome coding! ❤️‍🔥

**Comment by SkewedZeppelin** [comment]
https://github.com/AmnestyTech/investigations/tree/master/2021-07-18_nso is already included

but they aren't useful anyway because they are very old
any new ones released would also be burned
