### ISSUE TITLE
download progress

### ISSUE THREAD

**Issue by SynapseScribe** [Divested-Mobile/hypatia#44]
it is not clear from the ui when all the downloads are finished, some.bigger files take longer to download but nothing is shown

**Comment by SkewedZeppelin** [comment]
https://gitlab.com/divested-mobile/hypatia/-/issues/14#note_699591058

**Comment by SynapseScribe** [comment]
which is the main issue tracker. github or is it gitlab?

**Comment by SkewedZeppelin** [comment]
There is no primary one, I'm just linking you my response.

**Comment by SkewedZeppelin** [comment]
Download handling has been improved and a message is now shown when all databases have been updated.
