### ISSUE TITLE
How to get hypatia databases

### ISSUE THREAD

**Issue by Siradankullanici** [Divested-Mobile/hypatia#48]
I want to get hypatia databases to my project.

**Comment by SkewedZeppelin** [comment]
The scripts to generate them and their sources are in the scripts folder: https://github.com/Divested-Mobile/Hypatia/tree/stable/scripts

**Comment by Siradankullanici** [comment]
Can you manually upload it except clamav.

**Comment by Siradankullanici** [comment]
ok i got it no more need  your project.
