### ISSUE TITLE
Not scanning with shared internet  (Bluetooth tethering) and no physical sim card on the 2nd device (android)

### ISSUE THREAD

**Issue by robovoice1** [Divested-Mobile/hypatia#50]
To reproduce:

1. Share an internet connection with Bluetooth tethering.
2. Install Hypatia (fdroid) apk on the 2nd device
3. On the second (connected) device download the databases. (works as expected)
4. check all scanning options after tapping top right
Please watch screenshot1
5. Start the initial scanning process on the 2nd phone
6. After some time i get the message:
No database avaiable, not scanning...
Please watch screenshot2

Changing the physical sim card from smartphone1 to smartphone2 and restarting the scan solves this.
Please watch screenshot3

Google Pixel 6 pro
Android14 GrapheneOS alpha channel
UQ1A.231205.015.2023121200

Google Pixel 4a (device is end of life, just for testing)
Android 13 GrapheneOS alpha
TQ3A230805.001.S1.2023110900

![Screenshot_20231219-104556](https://github.com/Divested-Mobile/Hypatia/assets/92784377/8134eb93-fc80-4a97-a948-8b09ac2c8d12)
![Screenshot_20231219-111656](https://github.com/Divested-Mobile/Hypatia/assets/92784377/986e8620-b4e1-432f-9bec-d282c4730406)
![Screenshot_20231219-105156](https://github.com/Divested-Mobile/Hypatia/assets/92784377/d7fc45cb-9652-458a-b441-9d4503548be6)

**Comment by SkewedZeppelin** [comment]
Downloading over Bluetooth PAN should work, but it'll probably take 5+ minutes.
It does look like it did eventually load the expected signatures.

**Comment by robovoice1** [comment]
With the newest version of Hypatia this is functioning as expected :-) 
Thanks and good new year!
