### ISSUE TITLE
(Question) Successfully infiltrated device with Sherlock spyware can be detected with Hypatia?

### ISSUE THREAD

**Issue by robovoice1** [Divested-Mobile/hypatia#51]
Based on reports like this:

https://www.theregister.com/2023/09/16/insanet_spyware/

**Comment by SkewedZeppelin** [comment]
Unlikely.
The database needs an overhaul to be more effective, but there are space limitations.

**Comment by robovoice1** [comment]
Also thanks for answering this one.
Happy new year :-)

**Comment by SkewedZeppelin** [comment]
The database has since been overhauled.
Went from 440k signatures to 6.9 million.
You can optionally enable extended mode to detect another 40 million.
