### ISSUE TITLE
Hypatia marks .nomedia files as "potential matches"

### ISSUE THREAD

**Issue by exaCORE42** [Divested-Mobile/hypatia#54]
.nomedia files seem to be fairly routine files, so I was wondering if this was a bug.

**Comment by 1shira** [comment]
I have noticed this too, additonally scanning /system results in hypatia marking a lot of files, however on closer inspection, any of the marked files I could access, were 0B empty files, so were the .nomedia ones.
Therefore I do belive this is unintended behaviour.

However it also marked mgoogle.andriod.gms/base.apk as a potential match, which obviously should not be an empty file, leaving me wondering if this is an error too, or if somehow an Andriod System file got infected. Theoretically nothing should be able to write to such a file, except for a system update maybe, wich I did do recently, however I have also scanned my Andriod using other scanners and none have detected anything suspicious, so I really just don't know what to trust now.

Would be nice to know if hypatia is just bugged or if I have a problem on my hands

**Comment by XMA2l** [comment]
> I have noticed this too, additonally scanning /system results in hypatia marking a lot of files, however on closer inspection, any of the marked files I could access, were 0B empty files, so were the .nomedia ones.
> Therefore I do belive this is unintended behaviour.
> 
> However it also marked mgoogle.andriod.gms/base.apk as a potential match, which obviously should not be an empty file, leaving me wondering if this is an error too, or if somehow an Andriod System file got infected. Theoretically nothing should be able to write to such a file, except for a system update maybe, wich I did do recently, however I have also scanned my Andriod using other scanners and none have detected anything suspicious, so I really just don't know what to trust now.
> 
> Would be nice to know if hypatia is just bugged or if I have a problem on my hands

Your "mgoogle.andriod.gms/base.apk" is something i noticed to on a pals device - this isnt og google gms - (so probably no system app) have a closer look at the "*M*google"... - this seems to be a microG flavour - in my case it was " Vanced MicroG" from izzysofts fdroid mirror of its github repo - compatible with revanced! Googles system service aint having the "M" infront! 

Wanted to also ask about potential false positive right now - but a new thread is - probably - not neccesary now!?! 

Can someone confirm that vanilla microG isnt flagged? Or do u have microG vanilla? 

That vanced microg seems to be the mostly advised revanced microg as the commit history/servicibility of alternative revanced specific repos - wstadev/inotia - are potentially worse!?! So i read after a quick research - but seems to be controversial. Are those other versions flagged to?

**Comment by SkewedZeppelin** [comment]
This was fixed a week ago. You both need to update to the latest version 3.x.

And yes, the old Vanced microG is flagged: https://bazaar.abuse.ch/sample/e5ce4f9759d3e70ac479bf2d0707efe5a42fca8513cf387de583b8659dbfbbbf

You can run the lookup option on detections to see what they are.
