### ISSUE TITLE
Response code 404 when updating DDBB

### ISSUE THREAD

**Issue by peritumes** [Divested-Mobile/hypatia#56]
When manually try to update the DDBB from the preset "https://divested.dev/MalwareScannerSignatures/ no one file is downloaded and i get "Response code 404". It happens with all each one of the DDBB available to tick for downloading in ther app: ClamAV:Andorid Only, ClamAV: main, ClamAV: Daily, ESET, Targeted Threats, Amnesty tech and Stalkerware.

**Comment by SkewedZeppelin** [comment]
You need to update your app.
