### ISSUE TITLE
Matches found. Now what?

### ISSUE THREAD

**Issue by windowshopr** [Divested-Mobile/hypatia#59]
![Screenshot_20240111-000042](https://github.com/Divested-Mobile/Hypatia/assets/40477419/5c27e624-587c-412d-9cb2-6effda5a6411)

What files? Where? Quarantine? Known fixes? Beuhler?

**Comment by SkewedZeppelin** [comment]
You get a notification for all detections.

You can choose to lookup or delete each one.

If you didn't grant the app notification permission, you need to do that and scan again.

**Comment by windowshopr** [comment]
That's interesting, i just ran the scan again and got the notification when i didn't the first time i ran 2 scans upon first install. I verified that my notifications weren't blocked either, but its running. Thanks!

Only thing now is the match it found takes me to virus total, where it says the hash is not found. Could be an older database entry maybe?

**Comment by SkewedZeppelin** [comment]
The lookup option is opportunistic. It only sends the hash to VirusTotal.com, it will not upload the file.

If VT doesn't have it, it may be a false positive or they simply never seen it.

You can manually upload it to their website if you want to double check.
