### ISSUE TITLE
Server side database update schedule

### ISSUE THREAD

**Issue by user8446** [Divested-Mobile/hypatia#6]
Hi team,

I noticed that the rules database sometimes won't change for a while (as of today it shows no changes since 4/29, 4 days ago). Is there a schedule that the team updates it? This could also be automated if done manually.

Second, I assumed this rules file was going to ../us.spotco.malwarescanner but the directory doesn't even exist??

**Comment by SkewedZeppelin** [comment]
> team updates it

There is no team... it is just me, myself, and I.

> Is there a schedule

It is currently done manually, by hand.

I run `freshclam` then run https://github.com/Divested-Mobile/Hypatia/blob/stable/scripts/clamav.sh then I upload the files to the server.

> This could also be automated

I know it can be automated, it is low on my TODO list.

> this rules file was going to

Databases are stored in the apps internal storage directory.
eg. /data/data/0/us.spotco.malwarescanner/files/ or so

**Comment by user8446** [comment]
First thank you then for the development!!! It is MUCH appreciated!

Second, do you think it would be a good idea to switch to shared storage (I think, I'm not a Android dev) for the database? I could write a script to update daily and drop it into the directory and other users could add their own signatures from other sources as well

**Comment by SkewedZeppelin** [comment]
> switch to shared storage

That would not be a good idea.
I am not against users being able to add their own databases, but moving the primary ones into shared storage would allow a malicious app to edit them.
The unfinished recode planned to support custom databases.

**Comment by user8446** [comment]
Thank you, that makes sense on the storage.

**Comment by SkewedZeppelin** [comment]
There have been 83 databases updates in the past ~450 days, with at least one every week.

**Comment by SkewedZeppelin** [comment]
A little over a year has passed.
Still at one update a week.
172 updates have been made since July 19th 2021.
