### ISSUE TITLE
Publish releases with APK on GitHub

### ISSUE THREAD

**Issue by Penknife0915** [Divested-Mobile/hypatia#61]
There are [good reasons](https://privsec.dev/posts/android/f-droid-security-issues/) not to use F-Droid, so it would be nice to publish the developer-signed, independent APK.

**Comment by SkewedZeppelin** [comment]
None of those issues apply to the apks available via the divestos.org repo.

**Comment by SkewedZeppelin** [comment]
Use the official repo: https://divestos.org/pages/our_apps#repos
Or direct downloads: https://divestos.org/pages/our_apps#directDownloads
