### ISSUE TITLE
False positive detected in jpg pic taken on Google Camera

### ISSUE THREAD

**Issue by Fre148** [Divested-Mobile/hypatia#64]
Hi, don't know if this is the right place to report it.

Device: Pixel 7, stock OS
Hypatia version: 3.0.6 from F-Droid
Databases: Default, updated.
Scan options: Real-time, APKs, internal storage
Self test: Successful
Detection directory: DCIM/Camera
ID: 797dce83

This is the only detection, also, Play Protect shows all clear. Thank you!

**Comment by SkewedZeppelin** [comment]
Due to the nature of the bloom filter based database false positive like this will sometimes rarely happen.

They can't be excluded, it isn't actually in the database, just happens to be similar enough.

**Comment by Fre148** [comment]
Perfect! Thanks a lot for answering :)

**Comment by Fre148** [comment]
Solved 💯
