### ISSUE TITLE
False positive on hypatia file?

### ISSUE THREAD

**Issue by Coehill** [Divested-Mobile/hypatia#66]
I received an alert for a file with hypatia in the title which appears to be a false positive.

![3a1d7269-3706-4e5d-9838-4bec75eafab6](https://github.com/Divested-Mobile/Hypatia/assets/13023025/07be246a-261e-4de7-84da-0d7457f9c406)
![f9c10837-9b4e-470c-8687-be0c037ddab7](https://github.com/Divested-Mobile/Hypatia/assets/13023025/93eedd5a-c23c-4e51-a623-4317870e29ef)

This is the lookup for it:
https://www.virustotal.com/gui/file/3be403a831795482e82e2f9bc3e57ca34744aca3756e297b056b9f9c41830eaf/details

I'm unclear about what the self test is for but it is picking it up as malware.

**Comment by SkewedZeppelin** [comment]
That isn't a false positive. Those are the files created by the "Write self test files" button, which you very likely tapped at some point.

VirusTotal won't flag them since they're just harmless text files that say "HypatiaHypatiaHypatia".
