### ISSUE TITLE
Hypatia app not downloading databases, check logcat (Android 6)

### ISSUE THREAD

**Issue by git29feb** [Divested-Mobile/hypatia#73]
Hello,

both android 6 smartphones do not download or update the databases; it has been the case for the last couple of days.
No problem with Android 9.
Message: Failed to download, check logcat [(?)], All databases updated [(??1??)]
Last time the databases were updated (after last app update to version 3.06), the databases were downloaded.
Re-installing the app does not change anything.

Thank you for your help.

**Comment by SkewedZeppelin** [comment]
android 6 likely doesn't have the necessary certificates to use https with let's encrypt

you can try following this guide https://www.stoutner.com/lets-encrypt-isrg-root-x1-and-privacy-browser/

**Comment by git29feb** [comment]
It worked. THANK YOU
