### ISSUE TITLE
hypatia stops daily 

### ISSUE THREAD

**Issue by 1alexman1** [Divested-Mobile/hypatia#76]
I have samsung A105 and I use hypatia. Very often I found hypatia application closed, and I have to start it again, and again over 10 times a day. Is it possible samsung core or other hidden processes to stop the application?

**Comment by SkewedZeppelin** [comment]
that device only has 2GB of RAM
the system is likely terminating Hypatia to keep your focused apps running

**Comment by 1alexman1** [comment]
I have removed many of the useless applications and usually only have NetGuard, Hypatia, and WhatsApp open. It’s possible that 2GB of RAM may not be enough.
Thank you for answer.
