### ISSUE TITLE
system/xxxxx.vim detection

### ISSUE THREAD

**Issue by MarkoIndaco** [Divested-Mobile/hypatia#77]
Hi all, I just try Hypatia and after a scan i get some detections, all related to _usr/share/vim/syntax/xxxxx.vim_
Since the app offers scanning on VirusTotal I procede that way but result give ln is all files detected are clear. I don't know about this files .vim and would ask you if there's some action required by my side.
Phone is Xiaomi Mi 9 Lite - rooted Magisk with crDroid rom.
Thanks in advance.

**Comment by SkewedZeppelin** [comment]
I can exclude it, can you please provide the VirusTotal link or the hash from the notification?

**Comment by MarkoIndaco** [comment]
> I can exclude it, can you please provide the VirusTotal link or the hash from the notification?

Sure, I attack the notification and the related link to VT


![Hypatia detection](https://github.com/Divested-Mobile/Hypatia/assets/19596617/35888d0f-f4fe-432a-ad16-e256a00ceff1)

https://www.virustotal.com/gui/file/84d0841cd20892bc7989481fee179723ff216588f3e34a9bb56f7ee512689d8e

**Comment by MarkoIndaco** [comment]
Hi I got another detection, this time is about WhatsApp. Even in this case the lookup to VT result in clear.

![Uploading Hypatia - WhatsApp detection.jpg…]()


https://www.virustotal.com/gui/file/ca358758f6d27e6cf45272937977a748fd88391db679ceda7dc7bf1f005ee879

**Comment by SkewedZeppelin** [comment]
@MarkoIndaco 
please update your database, these false positives should be resolved for now
