### ISSUE TITLE
hypatia does not detect virus files on work profile

### ISSUE THREAD

**Issue by husenunicorn** [Divested-Mobile/hypatia#86]
I use insular, and when I downloaded a virus sample from ikarus in my work profile hypatia did not detect the virus. However, when I downloaded the personal profile, Hypatia detected it

**Comment by SkewedZeppelin** [comment]
Main and work profiles are completely separate, you have to run a second copy of any app you want in it.

**Comment by husenunicorn** [comment]
> Main and work profiles are completely separate, you have to run a second copy of any app you want in it.

OK, thanks for the response🙏, btw I'm using LineageOS 21 (Android 14) and it seems the settings are restricted from being able to be activated on the link scanner

![Screenshot_20240713-201553_Setelan](https://github.com/user-attachments/assets/d08a0bc2-a5c2-4760-a0bd-87e713d6c997)
![Screenshot_20240713-201607_Setelan](https://github.com/user-attachments/assets/c204f75f-80ce-40d2-9f34-aa0e24cc4380)

**Comment by SkewedZeppelin** [comment]
That is a standard android mechanism, there are steps here to enable: https://divestos.org/pages/faq#restrictedSetting
> Depending on the installation source, apps may have some special settings restricted. To allow: Settings > Apps > Special App Access > [the setting] > [the app] > confirm that it is greyed out > tap the icon there > then on that app info screen tap the 3dot in top right > Allow restricted settings.

**Comment by husenunicorn** [comment]
> That is a standard android mechanism, there are steps here to enable: https://divestos.org/pages/faq#restrictedSetting
> 
> > Depending on the installation source, apps may have some special settings restricted. To allow: Settings > Apps > Special App Access > [the setting] > [the app] > confirm that it is greyed out > tap the icon there > then on that app info screen tap the 3dot in top right > Allow restricted settings.

Thank you very much, now that it's working, I'll close this issue😀🙏

**Comment by husenunicorn** [comment]
> That is a standard android mechanism, there are steps here to enable: https://divestos.org/pages/faq#restrictedSetting
> 
> > Depending on the installation source, apps may have some special settings restricted. To allow: Settings > Apps > Special App Access > [the setting] > [the app] > confirm that it is greyed out > tap the icon there > then on that app info screen tap the 3dot in top right > Allow restricted settings.

Thank you very much, now that it's working, I'll close this issue😀🙏
