### ISSUE TITLE
[Question] How does apk scanning work?

### ISSUE THREAD

**Issue by bps86** [Divested-Mobile/hypatia#90]
So first, I don't have a sample apk for hypatia testing so Idk if it'll work. Also since hypatia have write test files, I figured trying to test them out. The results are great, it was able to scan all directory including hidden ones. The one part that it wasn't able to scan was when test files was inside the zip file. So I was wondering how the apk scanning work if it wasn't able to detect test files from zip. Was it only scan the apk format? Does it will extract apk file in temporary directory first then scan it? I'm quite curious.

**Comment by SkewedZeppelin** [comment]
Hypatia only scans whole files, it does not perform any extraction.

**Comment by bps86** [comment]
Hmm, so if it scans the apk, does that mean it will scan the whole apk file instead of the inside, was I correct?

**Comment by SkewedZeppelin** [comment]
Yes. For the sources Hypatia uses the hashes of malicious APKs are the whole file itself.

**Comment by bps86** [comment]
Hmm, I understand. Thanks for the info, it's really helpful
